[config]
model="GPT-5-pro"
fallback_models = ["gemini-2.5-pro", "gpt-5"]

[pr_description]
enable_pr_diagram = true
enable_help_text = true
enable_large_pr_handling = true
generate_ai_title = true
extra_instructions = ""

[pr_compliance]
enable_todo_scan = true
enable_help_text = true
enable_ticket_labels = true
enable_no_ticket_labels = true
check_pr_additional_content = true

[pr_code_suggestions]
enable_help_text = true
demand_code_suggestions_self_review = true
suggestions_depth = "exhaustive"
enable_suggestion_type_reuse = true
num_best_practice_suggestions = 100
num_code_suggestions_per_chunk = 100

[github_app]
pr_commands = [
    "/describe",
    "/compliance",
    "/improve",
    '/ask "Perform a review as a Security Expert. Create a Threat Model based on the STRIDE framework. If possible, generate a mermaid js diagram to summarize and explain threat vectors. If there are any critical security recommendations, list them. Use markdown to format and highlight headers, sections, sub-sections, list items, todo lists etc."'
]

[gitlab]
pr_commands = [
    "/describe",
    "/compliance",
    "/improve",
    '/ask "Perform a review as a Security Expert. Create a Threat Model based on the STRIDE framework. If possible, generate a mermaid js diagram to summarize and explain threat vectors. If there are any critical security recommendations, list them. Use markdown to format and highlight headers, sections, sub-sections, list items, todo lists etc."'
]

[bitbucket_app]
pr_commands = [
    "/describe",
    "/compliance",
    "/improve",
    '/ask "Perform a review as a Security Expert. Create a Threat Model based on the STRIDE framework. If possible, generate a mermaid js diagram to summarize and explain threat vectors. If there are any critical security recommendations, list them. Use markdown to format and highlight headers, sections, sub-sections, list items, todo lists etc."'
]
