[config]
model = "gemini-2.5-pro"
fallback_models = ["GPT-5-pro", "gpt-5"]

[pr_description]
enable_pr_diagram = true
enable_help_text = true
enable_large_pr_handling = true
generate_ai_title = true
extra_instructions = ""

[pr_compliance]
enable_todo_scan = true
enable_help_text = true
enable_ticket_labels = true
enable_no_ticket_labels = true
check_pr_additional_content = true
enable_codebase_duplication_section = false

[pr_code_suggestions]
enable_help_text = true
demand_code_suggestions_self_review = true
suggestions_depth = "exhaustive"
enable_suggestion_type_reuse = true
num_best_practice_suggestions = 100

[review_agent]
enabled = true
publish_output = true
enable_issues_agent = true
enable_compliance_agent = true

[github_app]
pr_commands = [
    "/agentic_review",
    "/describe",
    "/compliance",
    "/improve",
    '/custom_prompt --pr_custom_prompt.prompt="Suggest improvements as an frontend accessibility expert, security expert and performance optimization expert"',
]

[gitlab]
pr_commands = [
    "/agentic_review",
    "/describe",
    "/compliance",
    "/improve",
    '/custom_prompt --pr_custom_prompt.prompt="Suggest improvements as an frontend accessibility expert, security expert and performance optimization expert"',
]

[bitbucket_app]
pr_commands = [
    "/agentic_review",
    "/describe",
    "/compliance",
    "/improve",
    '/custom_prompt --pr_custom_prompt.prompt="Suggest improvements as an frontend accessibility expert, security expert and performance optimization expert"',
]
