name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  boring-todo-api-test:
    name: "üêç boring-todo-api :: test"
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Sri/boring-todo-api

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"

      - name: Dependencies
        run: poetry install

      - name: Test
        run: poetry run pytest
  
  boring-todo-app-test:
    name: "üåè boring-todo-app :: test"
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Sri/boring-todo-app

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Dependencies
        run: npm install

      - name: Test
        run: npm test